- name: "create backend app dir"
  file:
    path: ~/backend-app
    state: directory


- name: "create backend2 dir"
  file:
    path: ~/backend2
    state: directory

- name: "Unarchive backend file"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Unarchive backend2 file"
  unarchive:
    src: artifact2.tar.gz
    dest: ~/backend2

- name: "install nodejs package depandencies"
  shell: |
    cd ~/backend-app
    npm install


- name: "Run NodeJS backend app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: run_nodejs

- name: "Print message"
  debug:
    msg: "{{ run_nodejs.stdout_lines }}"