- name: "create backend app dir"
  file:
    path: ~/backend-app
    state: directory


- name: "Unarchive backend file"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app


- name: "install node depandencies"
  shell: |
    cd ~/backend-app
    npm i


- name: "Run NodeJS app with PM2"
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start main.js

  register: run_nodejs

- name: "Print message"
  debug:
    msg: "{{ run_nodejs.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save